eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
