spring:
  application:
    name: eureka-client-example
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}
      additionalZones: ${EUREKA_URI:http://localhost:9092/eureka}
  instance:
    preferIpAddress: false
    metadata-map:
      zone: zone1